name: Bot

on:
  push:
    paths:
      - 'bot/**'
      - 'pom.xml'
      - '.github/workflows/bot.yml' 


env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Maven
        run: mvn package -pl bot -am

      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
          run: docker build -t ghcr.io/${{ github.actor }}/bot-app:latest . -f bot/Dockerfile

      - name: Push image
        run: docker push ghcr.io/${{ github.actor }}/bot-app:latest
