app.test: 2

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  rabbit-queue: queue
  rabbit-exchange: exchange
  use-queue: true
  database-access-type: jpa
  scheduler:
    interval: 10000



server:
  port: 8081

spring:
  liquibase:
    enabled: false
  datasource:
    password: admin
    username: user
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scrapper

